---
title: Demo Programs
hero_image: images/banner.png
description: Learn how to run the Raspberry Pi demo programs
original_url: https://raspberrypi.org/learning/demo-programs
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Demo Programs
- title: Oh no! A command line interface!
- title: Hello world
- title: Hello video
- title: Hello triangle
- title: Hello triangle 2
- title: Hello teapot
- title: Hello audio
- title: What next?

