---
title: Demo Programs
hero_image: images/banner.png
description: Learn how to run the Raspberry Pi demo programs
original_url: https://raspberrypi.org/learning/demo-programs
theme: violet
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: ''
hardware: ''
software: ''
site_areas: projects
vesion: 4
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
- title: Demo Programs
- title: Oh no! A command line interface!
- title: Hello world
- title: Hello video
- title: Hello triangle
- title: Hello triangle 2
- title: Hello teapot
- title: Hello audio
- title: What next?

